# This has secrets! Do not use this config for anything but local testing
# with minikube.

# the binder apiToken bit requires jupyterhub helm-chart v0.5.x

rbac:
  enabled: true

custom:
  cors:
    allowOrigin: "*"

hub:
  cookieSecret: "36091e950f98f033aeae2520e2fe4c8599bc391598f910e510ad670765fbc1ff"
  db:
    type: "sqlite-memory"
  services:
    binder:
      admin: true
      apiToken: "aec7d32df938c0f55e54f09244a350cb29ea612907ed4f07be13d9553d18a8e4"
  allowNamedServers: false
  extraConfig:
    binder: |
      # get cors config from values.custom.cors
      import z2jh
      cors = z2jh.get_config('custom.cors', {})

      # image & token are set via spawn options
      from binderhub.spawner import AnonymousBinderSpawner
      c.AnonymousBinderSpawner.allow_origin = cors.get('allowOrigin')
      c.JupyterHub.spawner_class = AnonymousBinderSpawner

      # debug!
      c.JupyterHub.log_level = 10

singleuser:
  cmd: jupyter-notebook
  storage:
    type: none
  memory:
    guarantee: null
auth:
  type: custom
  custom:
    # disable login (users created exclusively via API)
    className: "nullauthenticator.NullAuthenticator"

prePuller:
  hook:
    enabled: false
  continuous:
    enabled: false

proxy:
  # Another secret!
  secretToken: "443fa28905c209eaf5803f911de7748f443c78062767d9d28d514dc4fbefd843"
  service:
    type: NodePort
    nodePorts:
      http: 30123
